// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qklzsctmyudyablvsyca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbHpzY3RteXVkeWFibHZzeWNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTA3NjcsImV4cCI6MjA3NDE4Njc2N30.1BoeVGDxs8DAS8ZcPKoO0OeFeXBnjvHndaNg_PpWfRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});